---
- name: Deploy Artifactory, see https://github.com/goern/artifactory-on-openshift
  tags:
    - openshift
    - artifactory
    - deploy

  hosts: localhost
  vars: # FIXME DRY
    openshift_master_url: https://acme-ocp3-haproxy-0.acme.e2e.bos.redhat.com:8443
    username: pltops
    password: password

  tasks:
  - name: verify oc version
    shell: "oc version"
    register: command_result
    failed_when:
      - "'oc v1.3.1' not in command_result.stdout"
      - "'oc v3.3' not in command_result.stdout"

  - name: login in OpenShift as administrator
    command: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift_master_url }}"

  - name: use Acme Corp IT Development infrastructure project
    command: "oc project acme-dev-infra"

  - name: create template for artifactory
    command: oc create -f ../openshift-template.yaml

  - name: create Artifactory default ConfigMap
    command: create configmap artifactory-default-config --from-file=../etc-opt-jfrog-artifactory-dist/

  - name: create Artifactory Pro application
    command: oc new-app --template=artifactory --param=ARTIFACTORY_IMAGE_NAME=artifactory-pro
